/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProximosRouteImport } from './routes/proximos'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AmanhaRouteImport } from './routes/amanha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'

const ProximosRoute = ProximosRouteImport.update({
  id: '/proximos',
  path: '/proximos',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AmanhaRoute = AmanhaRouteImport.update({
  id: '/amanha',
  path: '/amanha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amanha': typeof AmanhaRoute
  '/live': typeof LiveRoute
  '/proximos': typeof ProximosRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amanha': typeof AmanhaRoute
  '/live': typeof LiveRoute
  '/proximos': typeof ProximosRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amanha': typeof AmanhaRoute
  '/live': typeof LiveRoute
  '/proximos': typeof ProximosRoute
  '/events/$eventId': typeof EventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/amanha' | '/live' | '/proximos' | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/amanha' | '/live' | '/proximos' | '/events/$eventId'
  id: '__root__' | '/' | '/amanha' | '/live' | '/proximos' | '/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmanhaRoute: typeof AmanhaRoute
  LiveRoute: typeof LiveRoute
  ProximosRoute: typeof ProximosRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proximos': {
      id: '/proximos'
      path: '/proximos'
      fullPath: '/proximos'
      preLoaderRoute: typeof ProximosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amanha': {
      id: '/amanha'
      path: '/amanha'
      fullPath: '/amanha'
      preLoaderRoute: typeof AmanhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmanhaRoute: AmanhaRoute,
  LiveRoute: LiveRoute,
  ProximosRoute: ProximosRoute,
  EventsEventIdRoute: EventsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
