/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TomorrowRouteImport } from './routes/tomorrow'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as MultiplesRouteImport } from './routes/multiples'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as LeagueLeagueIdRouteImport } from './routes/league.$leagueId'
import { Route as ApiCronSnapshotRouteImport } from './routes/api/cron/snapshot'
import { Route as ApiCronResolveRouteImport } from './routes/api/cron/resolve'
import { Route as ApiCronRecalibrateRouteImport } from './routes/api/cron/recalibrate'

const TomorrowRoute = TomorrowRouteImport.update({
  id: '/tomorrow',
  path: '/tomorrow',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplesRoute = MultiplesRouteImport.update({
  id: '/multiples',
  path: '/multiples',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSnapshotRoute = ApiCronSnapshotRouteImport.update({
  id: '/api/cron/snapshot',
  path: '/api/cron/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronResolveRoute = ApiCronResolveRouteImport.update({
  id: '/api/cron/resolve',
  path: '/api/cron/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRecalibrateRoute = ApiCronRecalibrateRouteImport.update({
  id: '/api/cron/recalibrate',
  path: '/api/cron/recalibrate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/live': typeof LiveRoute
  '/multiples': typeof MultiplesRoute
  '/picks': typeof PicksRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/tomorrow': typeof TomorrowRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/api/cron/recalibrate': typeof ApiCronRecalibrateRoute
  '/api/cron/resolve': typeof ApiCronResolveRoute
  '/api/cron/snapshot': typeof ApiCronSnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/live': typeof LiveRoute
  '/multiples': typeof MultiplesRoute
  '/picks': typeof PicksRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/tomorrow': typeof TomorrowRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/api/cron/recalibrate': typeof ApiCronRecalibrateRoute
  '/api/cron/resolve': typeof ApiCronResolveRoute
  '/api/cron/snapshot': typeof ApiCronSnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/live': typeof LiveRoute
  '/multiples': typeof MultiplesRoute
  '/picks': typeof PicksRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/tomorrow': typeof TomorrowRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/api/cron/recalibrate': typeof ApiCronRecalibrateRoute
  '/api/cron/resolve': typeof ApiCronResolveRoute
  '/api/cron/snapshot': typeof ApiCronSnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/live'
    | '/multiples'
    | '/picks'
    | '/settings'
    | '/today'
    | '/tomorrow'
    | '/league/$leagueId'
    | '/match/$matchId'
    | '/player/$playerId'
    | '/team/$teamId'
    | '/api/cron/recalibrate'
    | '/api/cron/resolve'
    | '/api/cron/snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/live'
    | '/multiples'
    | '/picks'
    | '/settings'
    | '/today'
    | '/tomorrow'
    | '/league/$leagueId'
    | '/match/$matchId'
    | '/player/$playerId'
    | '/team/$teamId'
    | '/api/cron/recalibrate'
    | '/api/cron/resolve'
    | '/api/cron/snapshot'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/live'
    | '/multiples'
    | '/picks'
    | '/settings'
    | '/today'
    | '/tomorrow'
    | '/league/$leagueId'
    | '/match/$matchId'
    | '/player/$playerId'
    | '/team/$teamId'
    | '/api/cron/recalibrate'
    | '/api/cron/resolve'
    | '/api/cron/snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LiveRoute: typeof LiveRoute
  MultiplesRoute: typeof MultiplesRoute
  PicksRoute: typeof PicksRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  TomorrowRoute: typeof TomorrowRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
  ApiCronRecalibrateRoute: typeof ApiCronRecalibrateRoute
  ApiCronResolveRoute: typeof ApiCronResolveRoute
  ApiCronSnapshotRoute: typeof ApiCronSnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tomorrow': {
      id: '/tomorrow'
      path: '/tomorrow'
      fullPath: '/tomorrow'
      preLoaderRoute: typeof TomorrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiples': {
      id: '/multiples'
      path: '/multiples'
      fullPath: '/multiples'
      preLoaderRoute: typeof MultiplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/snapshot': {
      id: '/api/cron/snapshot'
      path: '/api/cron/snapshot'
      fullPath: '/api/cron/snapshot'
      preLoaderRoute: typeof ApiCronSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/resolve': {
      id: '/api/cron/resolve'
      path: '/api/cron/resolve'
      fullPath: '/api/cron/resolve'
      preLoaderRoute: typeof ApiCronResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/recalibrate': {
      id: '/api/cron/recalibrate'
      path: '/api/cron/recalibrate'
      fullPath: '/api/cron/recalibrate'
      preLoaderRoute: typeof ApiCronRecalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LiveRoute: LiveRoute,
  MultiplesRoute: MultiplesRoute,
  PicksRoute: PicksRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  TomorrowRoute: TomorrowRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
  ApiCronRecalibrateRoute: ApiCronRecalibrateRoute,
  ApiCronResolveRoute: ApiCronResolveRoute,
  ApiCronSnapshotRoute: ApiCronSnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
